<?php

namespace Database\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;

class Version00000000000012 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');
        $this->addSql('DROP TABLE IF EXISTS community_activity');
        $this->addSql('CREATE TABLE community_activity (activity_id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'活动id\', company_id BIGINT NOT NULL COMMENT \'公司ID\', chief_id BIGINT NOT NULL COMMENT \'团长ID\', activity_name VARCHAR(255) NOT NULL COMMENT \'活动名称\', activity_pics LONGTEXT NOT NULL COMMENT \'活动图片\', activity_desc VARCHAR(255) NOT NULL COMMENT \'活动简介\', activity_intro LONGTEXT NOT NULL COMMENT \'活动详细介绍\', start_time INT NOT NULL COMMENT \'开始时间\', end_time INT NOT NULL COMMENT \'结束时间\', activity_status VARCHAR(255) NOT NULL COMMENT \'活动状态 private私有 public公开 protected隐藏 success确认成团 fail成团失败\', delivery_status VARCHAR(255) DEFAULT \'PENDING\' NOT NULL COMMENT \'发货状态。可选值有 DONE—已发货;PENDING—待发货;SUCCESS-已收货\', delivery_time INT DEFAULT NULL COMMENT \'发货时间\', aftersales_setting VARCHAR(255) DEFAULT \'ban\' NOT NULL COMMENT \'售后配置 ban禁止售后\', created_at INT NOT NULL, updated_at INT DEFAULT NULL, INDEX ix_company_id (company_id), INDEX ix_chief_id (chief_id), INDEX ix_activity_name (activity_name), INDEX ix_start_time (start_time), INDEX ix_end_time (end_time), INDEX ix_activity_status (activity_status), PRIMARY KEY(activity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'社区拼团活动表\' ');
        $this->addSql('CREATE TABLE community_activity_item (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', activity_id BIGINT NOT NULL COMMENT \'活动ID\', goods_id BIGINT NOT NULL COMMENT \'商品spu ID\', item_id BIGINT NOT NULL COMMENT \'商品sku ID\', item_name VARCHAR(255) NOT NULL COMMENT \'商品名称\', item_spec_desc VARCHAR(255) DEFAULT NULL COMMENT \'商品规格描述\', item_brief VARCHAR(255) DEFAULT NULL COMMENT \'商品描述\', item_pics VARCHAR(255) DEFAULT NULL COMMENT \'商品图片\', price INT NOT NULL COMMENT \'销售价,单位为‘分’\', cost_price INT DEFAULT 0 COMMENT \'成本价,单位为‘分’\', market_price INT NOT NULL COMMENT \'原价,单位为‘分’\', store INT NOT NULL COMMENT \'库存数量\', created_at INT NOT NULL, updated_at INT DEFAULT NULL, INDEX ix_activity_id (activity_id), INDEX ix_item_id (item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'社区拼团活动商品表\' ');
        $this->addSql('CREATE TABLE community_activity_ziti (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', activity_id BIGINT NOT NULL COMMENT \'活动ID\', ziti_id BIGINT NOT NULL COMMENT \'自提ID\', condition_num INT NOT NULL COMMENT \'成团数量\', remark VARCHAR(255) DEFAULT NULL COMMENT \'备注\', INDEX ix_activity_id (activity_id), INDEX ix_ziti_id (ziti_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'社区拼团活动自提表\' ');
        $this->addSql('CREATE TABLE community_cart (cart_id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'购物车ID\', company_id BIGINT NOT NULL COMMENT \'公司id\', user_id BIGINT NOT NULL COMMENT \'用户id\', chief_id BIGINT NOT NULL COMMENT \'团长id\', activity_id BIGINT NOT NULL COMMENT \'活动id\', item_id BIGINT NOT NULL COMMENT \'商品id\', num BIGINT DEFAULT 1 NOT NULL COMMENT \'商品数量\', created INT NOT NULL, updated INT DEFAULT NULL, PRIMARY KEY(cart_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'社区团购购物车\' ');
        $this->addSql('CREATE TABLE community_chief (chief_id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'团长id\', company_id BIGINT NOT NULL COMMENT \'公司ID\', chief_name VARCHAR(255) NOT NULL COMMENT \'团长名称\', chief_avatar VARCHAR(255) NOT NULL COMMENT \'团长头像\', chief_mobile VARCHAR(255) NOT NULL COMMENT \'团长手机号\', chief_desc VARCHAR(255) NOT NULL COMMENT \'团长简介\', chief_intro LONGTEXT DEFAULT NULL COMMENT \'团长详细介绍\', province VARCHAR(255) DEFAULT NULL COMMENT \'省\', city VARCHAR(255) DEFAULT NULL COMMENT \'市\', area VARCHAR(255) DEFAULT NULL COMMENT \'区\', regions_id JSON DEFAULT NULL COMMENT \'地区编号集合(DC2Type:json_array)\', regions JSON DEFAULT NULL COMMENT \'地区名称集合(DC2Type:json_array)\', address VARCHAR(500) DEFAULT NULL COMMENT \'具体地址\', lng VARCHAR(255) DEFAULT NULL COMMENT \'地图纬度\', lat VARCHAR(255) DEFAULT NULL COMMENT \'地图经度\', user_id BIGINT DEFAULT 0 COMMENT \'会员ID\', created_at INT NOT NULL, updated_at INT DEFAULT NULL, INDEX ix_company_id (company_id), INDEX ix_chief_mobile (chief_mobile), INDEX ix_user_id (user_id), PRIMARY KEY(chief_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'社区拼团团长表\' ');
        $this->addSql('CREATE TABLE community_chief_distributor (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', chief_id BIGINT NOT NULL COMMENT \'团长ID\', distributor_id BIGINT NOT NULL COMMENT \'店铺ID\', bound_time BIGINT DEFAULT 0 COMMENT \'绑定时间\', INDEX ix_chief_id (chief_id), INDEX ix_distributor_id (distributor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'社区拼团团长关联店铺表\' ');
        $this->addSql('CREATE TABLE community_chief_ziti (ziti_id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'自提点id\', chief_id BIGINT NOT NULL COMMENT \'团长ID\', ziti_name VARCHAR(255) NOT NULL COMMENT \'自提点名称\', province VARCHAR(255) DEFAULT NULL COMMENT \'省\', city VARCHAR(255) DEFAULT NULL COMMENT \'市\', area VARCHAR(255) DEFAULT NULL COMMENT \'区\', regions_id JSON DEFAULT NULL COMMENT \'地区编号集合(DC2Type:json_array)\', regions JSON DEFAULT NULL COMMENT \'地区名称集合(DC2Type:json_array)\', address VARCHAR(500) DEFAULT NULL COMMENT \'具体地址\', lng VARCHAR(255) DEFAULT NULL COMMENT \'地图纬度\', lat VARCHAR(255) DEFAULT NULL COMMENT \'地图经度\', ziti_contact_user VARCHAR(255) DEFAULT NULL COMMENT \'自提点联系人\', ziti_contact_mobile VARCHAR(255) DEFAULT NULL COMMENT \'自提点联系电话\', ziti_pics VARCHAR(255) DEFAULT NULL COMMENT \'自提点图片\', is_default TINYINT(1) DEFAULT \'0\' COMMENT \'是否默认\', ziti_status VARCHAR(255) DEFAULT \'success\' COMMENT \'自提点状态 success正常 fail作废\', created_at INT NOT NULL, updated_at INT DEFAULT NULL, INDEX ix_chief_id (chief_id), INDEX ix_is_default (is_default), INDEX ix_ziti_status (ziti_status), PRIMARY KEY(ziti_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'社区拼团团长自提点管理表\' ');
        $this->addSql('CREATE TABLE community_items (goods_id BIGINT NOT NULL COMMENT \'商品ID\', company_id BIGINT NOT NULL COMMENT \'公司id\', distributor_id INT DEFAULT 0 NOT NULL COMMENT \'店铺id,为0时表示该商品为商城商品，否则为店铺自有商品\', min_delivery_num INT DEFAULT 0 NOT NULL COMMENT \'起送量\', sort INT DEFAULT 0 NOT NULL COMMENT \'商品排序\', created_at INT NOT NULL, updated_at INT DEFAULT NULL, INDEX ix_goods_id (goods_id), PRIMARY KEY(goods_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'社区拼团商品池\' ');
        $this->addSql('CREATE TABLE community_order_rel_activity (order_id BIGINT NOT NULL COMMENT \'订单号\', company_id BIGINT NOT NULL COMMENT \'公司id\', chief_id BIGINT NOT NULL COMMENT \'团长id\', chief_name VARCHAR(255) NOT NULL COMMENT \'团长名称\', chief_avatar VARCHAR(255) NOT NULL COMMENT \'团长头像\', activity_id BIGINT NOT NULL COMMENT \'活动id\', activity_name VARCHAR(255) NOT NULL COMMENT \'活动名称\', ziti_name VARCHAR(255) DEFAULT NULL COMMENT \'自提点名称\', ziti_address VARCHAR(500) DEFAULT NULL COMMENT \'具体地址\', lng VARCHAR(255) DEFAULT NULL COMMENT \'地图纬度\', lat VARCHAR(255) DEFAULT NULL COMMENT \'地图经度\', ziti_contact_user VARCHAR(255) DEFAULT NULL COMMENT \'自提点联系人\', ziti_contact_mobile VARCHAR(255) DEFAULT NULL COMMENT \'自提点联系电话\', activity_trade_no INT DEFAULT NULL COMMENT \'跟团号\', extra_data LONGTEXT DEFAULT NULL COMMENT \'附加信息\', created INT NOT NULL, updated INT DEFAULT NULL, PRIMARY KEY(order_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'社区团购购物车\' ');
        $this->addSql('ALTER TABLE companys CHANGE is_open_pc_template is_open_pc_template INT DEFAULT 1 COMMENT \'是否开启pc模板 1 开启 2不开启\', CHANGE menu_type menu_type INT DEFAULT 0 NOT NULL COMMENT \'菜单类型\'');
        $this->addSql('ALTER TABLE espier_uploadefile ADD operator_id BIGINT DEFAULT 0 COMMENT \'操作者id\'');
        $this->addSql('ALTER TABLE pages_template CHANGE template_title template_title VARCHAR(50) NOT NULL COMMENT \'模板名称\', CHANGE template_name template_name VARCHAR(50) NOT NULL COMMENT \'模板客户端名称\'');
        $this->addSql('ALTER TABLE wechat_authorization CHANGE nick_name nick_name VARCHAR(50) NOT NULL COMMENT \'昵称\', CHANGE user_name user_name VARCHAR(32) DEFAULT NULL COMMENT \'原始 ID\', CHANGE alias alias VARCHAR(50) DEFAULT NULL COMMENT \'授权方公众号所设置的微信号，可能为空\'');
        $this->addSql('ALTER TABLE wechat_weapp_setting CHANGE template_name template_name VARCHAR(50) NOT NULL COMMENT \'小程序模板名称\', CHANGE company_id company_id BIGINT NOT NULL COMMENT \'公司ID\', CHANGE page_name page_name VARCHAR(50) NOT NULL COMMENT \'页面名称\', CHANGE name name VARCHAR(50) NOT NULL COMMENT \'配置名称\', CHANGE version version VARCHAR(10) DEFAULT \'v1.0.0\' NOT NULL COMMENT \'配置版本\'');
        $this->addSql('ALTER TABLE wechat_weapp_template CHANGE template_name template_name VARCHAR(50) NOT NULL COMMENT \'小程序模板名称\', CHANGE template_open_status template_open_status VARCHAR(10) NOT NULL COMMENT \'小程序模板开通状态\'');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema): void
    {
    }
}
