<?php

namespace Database\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;

class Version00000000000006 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE aliyunsms_accesskey (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT NOT NULL COMMENT \'公司id\', accesskey_id VARCHAR(255) NOT NULL COMMENT \'accesskey_id\', accesskey_secret VARCHAR(255) NOT NULL COMMENT \'accesskey_secret\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_company_id (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'AccessKey表\' ');
        $this->addSql('CREATE TABLE aliyunsms_record (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT NOT NULL COMMENT \'公司id\', mobile VARCHAR(255) NOT NULL COMMENT \'手机号\', scene_id INT NOT NULL COMMENT \'场景ID\', task_id INT NOT NULL COMMENT \'任务ID\', template_code VARCHAR(255) NOT NULL COMMENT \'模板code\', sms_content VARCHAR(255) DEFAULT NULL COMMENT \'短信内容\', template_type VARCHAR(255) NOT NULL COMMENT \'短信类型:0：验证码;1：短信通知;2：推广短信;\', status VARCHAR(255) NOT NULL COMMENT \'发送状态:1-发送中;2-发送失败;3-发送成功\', biz_id VARCHAR(255) NOT NULL COMMENT \'发送回执ID\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_company_id (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'短信发送记录\' ');
        $this->addSql('CREATE TABLE aliyunsms_scene (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT NOT NULL COMMENT \'公司id\', scene_name VARCHAR(255) NOT NULL COMMENT \'场景名称\', scene_title VARCHAR(255) DEFAULT NULL COMMENT \'场景title\', template_type VARCHAR(255) NOT NULL COMMENT \'短信类型: 0：验证码;1：短信通知;2：推广短信;3：国际/港澳台消息\', status VARCHAR(255) NOT NULL COMMENT \'状态\', default_template VARCHAR(255) DEFAULT NULL COMMENT \'默认模板\', variables VARCHAR(255) DEFAULT NULL COMMENT \'模板变量\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_company_id (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'场景表\' ');
        $this->addSql('CREATE TABLE aliyunsms_scene_item (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT NOT NULL COMMENT \'公司id\', scene_id INT NOT NULL COMMENT \'场景ID\', sign_id INT NOT NULL COMMENT \'签名ID\', sign_name VARCHAR(255) NOT NULL COMMENT \'签名名称\', template_id INT NOT NULL COMMENT \'模板ID\', template_content LONGTEXT NOT NULL COMMENT \'模板内容\', status INT NOT NULL COMMENT \'0-未启用;1-已启用\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_company_id (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'场景实例表\' ');
        $this->addSql('CREATE TABLE aliyunsms_sign (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT NOT NULL COMMENT \'公司id\', sign_name VARCHAR(20) NOT NULL COMMENT \'签名名称\', sign_source VARCHAR(2) NOT NULL COMMENT \'签名来源\', remark VARCHAR(255) NOT NULL COMMENT \'签名申请说明\', sign_file LONGTEXT DEFAULT NULL COMMENT \'资质证明\', delegate_file LONGTEXT DEFAULT NULL COMMENT \'委托授权书\', status VARCHAR(2) NOT NULL COMMENT \'审核状态:0-审核中;1-审核通过;2-审核失败\', reason VARCHAR(255) DEFAULT NULL COMMENT \'审核备注\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_company_id (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'短信签名表\' ');
        $this->addSql('CREATE TABLE aliyunsms_task (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT NOT NULL COMMENT \'公司id\', task_name VARCHAR(255) NOT NULL COMMENT \'任务名称\', sign_id INT NOT NULL COMMENT \'签名ID\', template_id INT NOT NULL COMMENT \'模板id\', template_name VARCHAR(255) NOT NULL COMMENT \'模板名称\', user_id LONGTEXT NOT NULL COMMENT \'会员id\', status VARCHAR(255) NOT NULL COMMENT \'发送状态:1-等待中;2-发送成功;3-发送失败;4-已撤销\', send_at INT NOT NULL COMMENT \'发送时间\', total_num INT NOT NULL COMMENT \'号码数量\', failed_num INT NOT NULL COMMENT \'失败号码数量\', is_send INT NOT NULL COMMENT \'是否已发送\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_company_id (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'短信群发任务\' ');
        $this->addSql('CREATE TABLE aliyunsms_template (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'模板ID\', company_id BIGINT NOT NULL COMMENT \'公司id\', template_type VARCHAR(255) NOT NULL COMMENT \'短信类型: 0：验证码;1：短信通知;2：推广短信;3：国际/港澳台消息\', template_name VARCHAR(255) NOT NULL COMMENT \'模板名称\', remark VARCHAR(255) NOT NULL COMMENT \'模板申请说明\', template_content LONGTEXT NOT NULL COMMENT \'模板内容\', scene_id INT NOT NULL COMMENT \'短信场景\', template_code VARCHAR(255) DEFAULT NULL COMMENT \'模板编码\', status VARCHAR(255) NOT NULL COMMENT \'审核状态:0-审核中;1-审核通过;2-审核失败\', reason VARCHAR(255) DEFAULT NULL COMMENT \'审核备注\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_company_id (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'模板表\' ');
        $this->addSql('CREATE TABLE promotions_employee_purchase (purchase_id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'员工内购活动id\', company_id BIGINT NOT NULL COMMENT \'公司ID\', purchase_name VARCHAR(50) NOT NULL COMMENT \'员工内购活动名称\', ad_pic VARCHAR(255) DEFAULT NULL COMMENT \'活动广告图\', used_roles VARCHAR(255) NOT NULL COMMENT \'适用角色集合 employee:员工;dependents:家属;\', employee_limitfee INT UNSIGNED NOT NULL COMMENT \'员工额度，以分为单位\', is_share_limitfee TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'家属是否共有额度 0:否 1:是\', dependents_limitfee INT UNSIGNED NOT NULL COMMENT \'家属额度，以分为单位\', dependents_limit INT DEFAULT 0 NOT NULL COMMENT \'员工邀请家属上限\', begin_time INT NOT NULL COMMENT \'起始时间\', end_time INT NOT NULL COMMENT \'截止时间\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_company_id (company_id), PRIMARY KEY(purchase_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'员工内购活动规则表\' ');
        $this->addSql('CREATE TABLE promotions_employee_purchase_items (purchase_id BIGINT NOT NULL COMMENT \'员工内购活动ID\', item_id BIGINT NOT NULL COMMENT \'关联id(商品ID，标签ID，品牌ID等)\', company_id BIGINT NOT NULL COMMENT \'公司ID\', item_type VARCHAR(255) DEFAULT \'all\' NOT NULL COMMENT \'活动商品类型: all:全部商品,item:指定商品,tag:标签,category:商品主类目,brand:品牌\', limit_fee INT UNSIGNED NOT NULL COMMENT \'每人额度，以分为单位\', limit_num INT DEFAULT 0 NOT NULL COMMENT \'每人限购\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_company_id (company_id), INDEX idx_purchase_id (purchase_id), INDEX idx_item_id (item_id), PRIMARY KEY(purchase_id, item_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'员工内购商品表\' ');
        $this->addSql('CREATE TABLE promotions_employee_purchase_relorder (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', company_id BIGINT NOT NULL COMMENT \'公司ID\', purchase_id BIGINT NOT NULL COMMENT \'员工内购活动ID\', order_id VARCHAR(100) DEFAULT NULL COMMENT \'订单编号\', order_item_id BIGINT NOT NULL COMMENT \'订单中的商品ID\', user_id BIGINT NOT NULL COMMENT \'会员ID\', purchase_item_id BIGINT NOT NULL COMMENT \'员工内购商品id(商品ID，标签ID，品牌ID、商品主类目ID)\', num INT UNSIGNED NOT NULL COMMENT \'购买商品数量\', fee INT UNSIGNED NOT NULL COMMENT \'金额，以分为单位\', redis_key VARCHAR(255) NOT NULL COMMENT \'redis存储的key\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_company_id (company_id), INDEX idx_purchase_id (purchase_id), INDEX idx_order_id (order_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'员工内购订单关联表\' ');
        $this->addSql('CREATE TABLE promotions_employee_purchase_reluser (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', company_id BIGINT NOT NULL COMMENT \'公司ID\', purchase_id BIGINT NOT NULL COMMENT \'员工内购活动ID\', employee_user_id BIGINT NOT NULL COMMENT \'员工会员ID\', dependents_user_id BIGINT NOT NULL COMMENT \'家属会员ID\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_company_id (company_id), INDEX idx_purchase_id (purchase_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'员工内购家属关联表\' ');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema): void
    {
    }
}
