<?php

namespace Database\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;

class Version00000000000005 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE company_rel_delivery (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT NOT NULL COMMENT \'公司id\', type TINYINT(1) NOT NULL COMMENT \'配送类型【1 商家自配-按整单计算】【2 商家自配-按距离计算】\', status TINYINT(1) NOT NULL COMMENT \'状态【1 启用】【0 禁用】\', rules LONGTEXT NOT NULL COMMENT \'json存储，运费规则\', other_params LONGTEXT NOT NULL COMMENT \'json存储，其他参数\', created INT DEFAULT NULL COMMENT \'创建时间\', updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_company_id (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'商城关联配送配置表\' ');
        $this->addSql('CREATE TABLE datacube_merchant_data (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', count_date DATE NOT NULL COMMENT \'日期\', company_id BIGINT NOT NULL COMMENT \'公司ID\', member_count INT DEFAULT 0 NOT NULL COMMENT \'新增会员数\', aftersales_count INT DEFAULT 0 NOT NULL COMMENT \'新增售后单数\', refunded_count INT DEFAULT 0 NOT NULL COMMENT \'新增退款额\', amount_payed_count BIGINT DEFAULT 0 NOT NULL COMMENT \'新增交易额\', amount_point_payed_count BIGINT DEFAULT 0 NOT NULL COMMENT \'新增交易额(积分)\', order_count INT DEFAULT 0 NOT NULL COMMENT \'新增订单数\', order_point_count INT DEFAULT 0 NOT NULL COMMENT \'新增订单数(积分)\', order_payed_count INT DEFAULT 0 NOT NULL COMMENT \'新增已付款订单数\', order_point_payed_count INT DEFAULT 0 NOT NULL COMMENT \'新增已付款订单数(积分)\', gmv_count BIGINT DEFAULT 0 NOT NULL COMMENT \'新增gmv\', gmv_point_count BIGINT DEFAULT 0 NOT NULL COMMENT \'新增gmv(积分)\', merchant_id BIGINT DEFAULT 0 NOT NULL COMMENT \'商户id\', UNIQUE INDEX ix_date_company (count_date, company_id, merchant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'商户数据统计表\' ');
        $this->addSql('CREATE TABLE distribution_distributor_geofence (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'自增id\', company_id BIGINT NOT NULL COMMENT \'公司id\', distributor_id BIGINT NOT NULL COMMENT \'店铺id\', config_service_local_id BIGINT NOT NULL COMMENT \'地图配置的本地主键ID\', geofence_id BIGINT NOT NULL COMMENT \'第三方服务的围栏ID\', geofence_data LONGTEXT NOT NULL COMMENT \'json数据，第三方服务的围栏信息\', status SMALLINT DEFAULT 1 NOT NULL COMMENT \'状态【1 启用】【0 禁用】\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX ix_company_distributor_service (company_id, distributor_id, config_service_local_id, status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'店铺围栏信息\' ');
        $this->addSql('CREATE TABLE map_config_service (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'本地的唯一id，如果外部表要与该表做关联，需要使用该id\', company_id BIGINT NOT NULL COMMENT \'公司company id\', config_id BIGINT NOT NULL COMMENT \'地图配置的id\', type SMALLINT NOT NULL COMMENT \'服务的类型\', service_id VARCHAR(20) NOT NULL COMMENT \'第三方平台提供的服务id\', service_data LONGTEXT NOT NULL COMMENT \'json内容，第三方平台中的服务数据\', status SMALLINT DEFAULT 1 NOT NULL COMMENT \'状态【1 生效】【0 失效】\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX ix_company_config_type (company_id, config_id, type, status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'地图配置表\' ');
        $this->addSql('CREATE TABLE merchant (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT DEFAULT NULL COMMENT \'公司id\', settlement_apply_id BIGINT DEFAULT NULL COMMENT \'入驻申请id\', merchant_name VARCHAR(255) DEFAULT NULL COMMENT \'商户名称\', merchant_type_id BIGINT NOT NULL COMMENT \'商户类型ID\', settled_type VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'商户入驻类型。enterprise:企业;soletrader:个体户\', social_credit_code_id VARCHAR(255) DEFAULT NULL COMMENT \'统一社会信用代码\', province VARCHAR(50) DEFAULT NULL, city VARCHAR(50) DEFAULT NULL, area VARCHAR(50) DEFAULT NULL, regions_id LONGTEXT DEFAULT NULL COMMENT \'国家行政区划编码组合，逗号隔开\', address VARCHAR(255) DEFAULT NULL COMMENT \'详细地址\', legal_name VARCHAR(500) NOT NULL COMMENT \'联系人\', legal_cert_id VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'法人身份证号码\', legal_mobile VARCHAR(255) DEFAULT NULL COMMENT \'法人手机号码\', email VARCHAR(255) DEFAULT NULL COMMENT \'联系邮箱\', bank_acct_type VARCHAR(10) DEFAULT \'\' NOT NULL COMMENT \'银行账户类型：1-对公；2-对私\', card_id_mask VARCHAR(255) NOT NULL COMMENT \'结算银行卡号\', bank_name VARCHAR(100) DEFAULT NULL COMMENT \'结算银行卡所属银行名称\', bank_mobile VARCHAR(255) DEFAULT NULL COMMENT \'银行预留手机号\', license_url VARCHAR(255) DEFAULT NULL COMMENT \'营业执照图片url\', legal_certid_front_url VARCHAR(255) DEFAULT NULL COMMENT \'法人手持身份证正面url\', legal_cert_id_back_url VARCHAR(255) DEFAULT NULL COMMENT \'法人手持身份证反面url\', bank_card_front_url VARCHAR(255) DEFAULT NULL COMMENT \'结算银行卡正面url\', contract_url VARCHAR(255) DEFAULT NULL COMMENT \'合同url\', settled_succ_sendsms VARCHAR(10) DEFAULT \'1\' NOT NULL COMMENT \'入驻成功发送时间  1:立即 2:商家H5确认入驻协议后\', audit_goods TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'是否需要平台审核商品 0:不需要 1:需要\', source VARCHAR(30) DEFAULT \'h5\' COMMENT \'来源 admin:平台管理员;h5:h5入驻;\', disabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'禁用\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_company_id (company_id), INDEX idx_settlement_apply_id (settlement_apply_id), INDEX idx_legal_mobile (legal_mobile(64)), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'商户表\' ');
        $this->addSql('CREATE TABLE merchant_settlement_apply (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT DEFAULT NULL COMMENT \'公司id\', mobile VARCHAR(255) NOT NULL COMMENT \'手机号\', is_agree_agreement TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'是否同意入驻协议\', merchant_type_id BIGINT DEFAULT 0 NOT NULL COMMENT \'商户类型ID\', settled_type VARCHAR(255) DEFAULT \'\' COMMENT \'入驻类型。enterprise:企业;soletrader:个体户\', merchant_name VARCHAR(255) DEFAULT NULL COMMENT \'商户名称\', social_credit_code_id VARCHAR(255) DEFAULT NULL COMMENT \'统一社会信用代码\', province VARCHAR(50) DEFAULT NULL, city VARCHAR(50) DEFAULT NULL, area VARCHAR(50) DEFAULT NULL, regions_id LONGTEXT DEFAULT NULL COMMENT \'国家行政区划编码组合，逗号隔开\', address VARCHAR(255) DEFAULT NULL COMMENT \'详细地址\', legal_name VARCHAR(50) DEFAULT NULL COMMENT \'法人姓名\', legal_cert_id VARCHAR(255) DEFAULT \'\' COMMENT \'法人身份证号码\', legal_mobile VARCHAR(255) DEFAULT NULL COMMENT \'法人手机号码\', bank_acct_type VARCHAR(10) DEFAULT \'\' COMMENT \'银行账户类型：1-对公；2-对私\', card_id_mask VARCHAR(255) DEFAULT NULL COMMENT \'结算银行卡号\', bank_name VARCHAR(100) DEFAULT NULL COMMENT \'结算银行卡所属银行名称\', bank_mobile VARCHAR(255) DEFAULT NULL COMMENT \'银行预留手机号\', license_url VARCHAR(255) DEFAULT NULL COMMENT \'营业执照图片url\', legal_certid_front_url VARCHAR(255) DEFAULT NULL COMMENT \'法人手持身份证正面url\', legal_cert_id_back_url VARCHAR(255) DEFAULT NULL COMMENT \'法人手持身份证反面url\', bank_card_front_url VARCHAR(255) DEFAULT NULL COMMENT \'结算银行卡正面url\', audit_status VARCHAR(10) DEFAULT \'1\' COMMENT \'审核状态：1:审核中 2:审核成功 3:审核驳回\', audit_memo VARCHAR(500) DEFAULT NULL COMMENT \'审核备注\', source VARCHAR(30) DEFAULT \'h5\' COMMENT \'来源 admin:平台管理员;h5:h5入驻;\', audit_goods TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'是否需要平台审核商品 0:不需要 1:需要\', disabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'禁用\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_company_id (company_id), INDEX idx_audit_status (audit_status), INDEX idx_settled_type (settled_type), INDEX idx_source (source), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'商户入驻申请表\' ');
        $this->addSql('CREATE TABLE merchant_type (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT DEFAULT NULL COMMENT \'公司id\', name VARCHAR(50) NOT NULL COMMENT \'商户类型名称\', parent_id BIGINT DEFAULT 0 NOT NULL COMMENT \'父级id, 0为顶级\', path VARCHAR(255) DEFAULT \'0\' COMMENT \'路径\', sort BIGINT DEFAULT 0 COMMENT \'排序\', is_show TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'是否显示\', level INT DEFAULT 1 COMMENT \'等级\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_company_id (company_id), INDEX idx_name (name), INDEX idx_parent_id (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'商户类型表\' ');
        $this->addSql('ALTER TABLE aftersales ADD merchant_id BIGINT DEFAULT 0 NOT NULL COMMENT \'商户id\'');
        $this->addSql('CREATE INDEX idx_merchant_id ON aftersales (merchant_id)');
        $this->addSql('ALTER TABLE aftersales_refund ADD merchant_id BIGINT DEFAULT 0 NOT NULL COMMENT \'商户id\'');
        $this->addSql('CREATE INDEX idx_merchant_id ON aftersales_refund (merchant_id)');
        $this->addSql('ALTER TABLE companys_operator_logs ADD merchant_id BIGINT DEFAULT 0 NOT NULL COMMENT \'商户id\'');
        $this->addSql('ALTER TABLE datacube_distributor_data ADD merchant_id BIGINT DEFAULT 0 NOT NULL COMMENT \'商户id\'');
        $this->addSql('ALTER TABLE datacube_goods_data ADD merchant_id BIGINT DEFAULT 0 NOT NULL COMMENT \'商户id\'');
        $this->addSql('ALTER TABLE distribution_distributor ADD introduce LONGTEXT DEFAULT NULL COMMENT \'店铺介绍\', ADD merchant_id BIGINT DEFAULT 0 NOT NULL COMMENT \'商户id\', ADD distribution_type SMALLINT DEFAULT 0 NOT NULL COMMENT \'店铺类型:0:自营,1:加盟\', CHANGE created created bigint NOT NULL, CHANGE updated updated bigint NOT NULL');
        $this->addSql('CREATE INDEX idx_merchant_id ON distribution_distributor (merchant_id)');
        $this->addSql('ALTER TABLE distributor_aftersales_address ADD merchant_id BIGINT DEFAULT 0 NOT NULL COMMENT \'商户id\', CHANGE created created bigint NOT NULL, CHANGE updated updated bigint NOT NULL');
        $this->addSql('ALTER TABLE espier_export_log ADD merchant_id BIGINT DEFAULT 0 NOT NULL COMMENT \'商户id\'');
        $this->addSql('ALTER TABLE operator_data_pass ADD merchant_id BIGINT DEFAULT 0 NOT NULL COMMENT \'商户id\'');
        $this->addSql('CREATE INDEX idx_merchant_id ON operator_data_pass (merchant_id)');
        $this->addSql('ALTER TABLE operators ADD merchant_id BIGINT DEFAULT 0 COMMENT \'商户id\', ADD is_merchant_main VARCHAR(255) DEFAULT \'0\' NOT NULL COMMENT \'是否是商户端超级管理员  1：是   0：不是\', CHANGE operator_type operator_type VARCHAR(255) DEFAULT \'admin\' NOT NULL COMMENT \'操作员类型类型。admin:超级管理员;staff:员工;distributor:店铺管理员;dealer:经销商;merchant:商户\'');
        $this->addSql('ALTER TABLE orders_normal_orders ADD merchant_id BIGINT DEFAULT 0 NOT NULL COMMENT \'商户id\', CHANGE receipt_type receipt_type VARCHAR(255) DEFAULT \'logistics\' NOT NULL COMMENT \'收货方式。可选值有 【logistics 物流】【ziti 店铺自提】【dada 达达同城配】【merchant 商家自配】\'');
        $this->addSql('CREATE INDEX idx_merchant_id ON orders_normal_orders (merchant_id)');
        $this->addSql('ALTER TABLE refund_error_logs ADD merchant_id BIGINT DEFAULT 0 NOT NULL COMMENT \'商户id\'');
        $this->addSql('CREATE INDEX idx_merchant_id ON refund_error_logs (merchant_id)');
        $this->addSql('ALTER TABLE shop_menu CHANGE version version SMALLINT DEFAULT 1 NOT NULL COMMENT \'菜单版本,1:商家菜单;2:平台菜单,3:店铺菜单,4:供应商菜单,5:经销商菜单,6:商户菜单\'');
        $this->addSql('ALTER TABLE trade ADD merchant_id BIGINT DEFAULT 0 NOT NULL COMMENT \'商户id\'');
        $this->addSql('CREATE INDEX idx_merchant_id ON trade (merchant_id)');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema): void
    {
    }
}
