<?php

namespace Database\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;

class Version00000000000032 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE wsugc_badge (badge_id BIGINT AUTO_INCREMENT NOT NULL, badge_name VARCHAR(250) NOT NULL COMMENT \'角标名称\', badge_memo VARCHAR(250) DEFAULT NULL COMMENT \'角标备注\', mobile VARCHAR(50) DEFAULT NULL COMMENT \'手机号\', p_order INT DEFAULT 0 NOT NULL COMMENT \'排序\', created INT UNSIGNED NOT NULL COMMENT \'添加时间\', updated INT DEFAULT NULL, ai_verify_time BIGINT DEFAULT 0 COMMENT \'机器审核时间\', manual_verify_time BIGINT DEFAULT 0 COMMENT \'人工审核时间\', company_id BIGINT NOT NULL, enabled INT DEFAULT 1 NOT NULL COMMENT \'是否启用.\', status INT DEFAULT 0 NOT NULL COMMENT \'审核状态(0待审核,1审核通过,2机器拒绝,3待人工审核,4人工拒绝)\', ai_refuse_reason VARCHAR(255) DEFAULT NULL COMMENT \'机器拒绝理由\', manual_refuse_reason VARCHAR(255) DEFAULT NULL COMMENT \'人工拒绝理由\', is_top INT DEFAULT 0 NOT NULL COMMENT \'是否置顶.\', user_id BIGINT DEFAULT 0 NOT NULL COMMENT \'创建的用户\', source INT DEFAULT 1 COMMENT \'来源 1用户,2官方\', operator_id BIGINT DEFAULT 0 COMMENT \'管理员id\', INDEX idx_user_id (user_id), INDEX idx_company_id (company_id), INDEX idx_mobile (mobile), PRIMARY KEY(badge_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'角标\' ');
        $this->addSql('CREATE TABLE wsugc_comment (comment_id BIGINT AUTO_INCREMENT NOT NULL, post_id BIGINT NOT NULL COMMENT \'笔记id\', user_id BIGINT NOT NULL COMMENT \'用户id\', parent_comment_id BIGINT NOT NULL COMMENT \'父级评论id\', reply_comment_id BIGINT NOT NULL COMMENT \'回复评论id\', reply_user_id BIGINT NOT NULL COMMENT \'回复会员id\', content LONGTEXT DEFAULT NULL COMMENT \'内容\', likes VARCHAR(255) NOT NULL COMMENT \'点赞数\', ip VARCHAR(255) DEFAULT NULL COMMENT \'ip\', province VARCHAR(255) DEFAULT NULL COMMENT \'省份\', city VARCHAR(255) DEFAULT NULL COMMENT \'城市\', district VARCHAR(255) DEFAULT NULL COMMENT \'区县\', p_order INT DEFAULT 0 COMMENT \'排序\', status INT DEFAULT 0 NOT NULL COMMENT \'审核状态(0待审核,1审核通过,2机器拒绝,3待人工审核,4人工拒绝)\', enable INT DEFAULT 1 NOT NULL COMMENT \'上架状态(0下架,1上架)\', disabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'是否无效\', created INT NOT NULL, updated INT DEFAULT NULL, ai_verify_time BIGINT DEFAULT 0 COMMENT \'机器审核时间\', manual_verify_time BIGINT DEFAULT 0 COMMENT \'人工审核时间\', ai_refuse_reason VARCHAR(255) DEFAULT NULL COMMENT \'机器拒绝理由\', manual_refuse_reason VARCHAR(255) DEFAULT NULL COMMENT \'人工拒绝理由\', company_id BIGINT NOT NULL, PRIMARY KEY(comment_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'笔记评论\' ');
        $this->addSql('CREATE TABLE wsugc_comment_like (comment_like_id BIGINT AUTO_INCREMENT NOT NULL, post_id BIGINT NOT NULL COMMENT \'笔记id\', comment_id BIGINT NOT NULL COMMENT \'评论id\', user_id BIGINT NOT NULL COMMENT \'会员id\', disabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'是否无效\', created bigint NOT NULL, updated bigint NOT NULL, INDEX idx_post_id (post_id), INDEX idx_comment_id (comment_id), INDEX idx_disabled (disabled), PRIMARY KEY(comment_like_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'评论点赞\' ');
        $this->addSql('CREATE TABLE wsugc_follower (follower_id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'id\', user_id BIGINT NOT NULL COMMENT \'会员id\', follower_user_id BIGINT NOT NULL COMMENT \'粉丝会员id\', disabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'是否无效\', company_id BIGINT NOT NULL, created bigint NOT NULL, updated bigint NOT NULL, PRIMARY KEY(follower_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE wsugc_image_tag (image_tag_id BIGINT AUTO_INCREMENT NOT NULL, image_id BIGINT NOT NULL COMMENT \'图片id\', tag_id BIGINT NOT NULL COMMENT \'标签id\', enabled INT DEFAULT 1 NOT NULL COMMENT \'是否启用\', created INT NOT NULL, updated INT DEFAULT NULL, company_id BIGINT NOT NULL, INDEX idx_image_id (image_id), INDEX idx_tag_id (tag_id), PRIMARY KEY(image_tag_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'图片tag关联表\' ');
        $this->addSql('CREATE TABLE wsugc_message (message_id BIGINT AUTO_INCREMENT NOT NULL, type VARCHAR(255) NOT NULL COMMENT \'消息类型.system系统消息;replyPost回复消息likePost笔记点赞 favoritePost收藏笔记 followerUser关注了您\', sub_type VARCHAR(255) NOT NULL COMMENT \'消息类型及子类型.系统消息(system):approve通过,reject拒绝,unenable下架; 回复消息(reply):replyPost评论了您的笔记,replyComment回复了您的评论; 收藏笔记(favoritePost):favorite收藏,unfavorite取消收藏; 关注(followerUser):follow关注,unfollow取关;  点赞(like):likePost点赞笔记,likeComment点赞评论\', source INT DEFAULT 1 COMMENT \'来源 1用户,2官方(系统通知)\', from_user_id BIGINT DEFAULT 0 NOT NULL COMMENT \'来自用户\', from_nickname VARCHAR(255) DEFAULT \'\' COMMENT \'来自昵称\', to_user_id BIGINT DEFAULT 0 NOT NULL COMMENT \'发给用户\', to_nickname VARCHAR(255) DEFAULT \'\' COMMENT \'发给昵称\', post_id BIGINT DEFAULT 0 NOT NULL COMMENT \'笔记id\', comment_id BIGINT DEFAULT 0 COMMENT \'评论id\', title VARCHAR(255) DEFAULT NULL COMMENT \'通知标题\', content VARCHAR(255) DEFAULT NULL COMMENT \'通知内容\', created INT UNSIGNED NOT NULL COMMENT \'添加时间\', updated INT DEFAULT NULL, company_id BIGINT NOT NULL, hasread TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'是否已读.\', INDEX idx_to_user_id (to_user_id), INDEX idx_type (type), INDEX idx_post_id (post_id), INDEX idx_comment_id (comment_id), INDEX idx_hasread (hasread), INDEX idx_company_id (company_id), PRIMARY KEY(message_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'消息\' ');
        $this->addSql('CREATE TABLE wsugc_post (post_id BIGINT AUTO_INCREMENT NOT NULL, user_id BIGINT NOT NULL COMMENT \'用户id\', operator_id BIGINT DEFAULT 0 COMMENT \'管理员id\', source INT DEFAULT 1 COMMENT \'来源 1用户,2官方\', title VARCHAR(255) NOT NULL COMMENT \'标题\', likes INT NOT NULL COMMENT \'点赞数\', ip VARCHAR(255) DEFAULT NULL COMMENT \'ip地址\', mobile VARCHAR(255) DEFAULT NULL COMMENT \'手机号\', cover VARCHAR(255) DEFAULT NULL COMMENT \'封面图\', video VARCHAR(255) DEFAULT NULL COMMENT \'视频\', video_ratio VARCHAR(255) DEFAULT NULL COMMENT \'视频比例\', video_place VARCHAR(255) DEFAULT NULL COMMENT \'视频位置\', video_thumb VARCHAR(255) DEFAULT NULL COMMENT \'视频缩略图\', position VARCHAR(255) DEFAULT NULL COMMENT \'坐标\', is_top INT DEFAULT 0 NOT NULL COMMENT \'是否置顶.\', address VARCHAR(255) DEFAULT NULL COMMENT \'地址\', topics LONGTEXT DEFAULT NULL COMMENT \'话题\', badges LONGTEXT DEFAULT NULL COMMENT \'角标\', goods LONGTEXT DEFAULT NULL COMMENT \'商品\', images LONGTEXT DEFAULT NULL COMMENT \'多图\', image_path LONGTEXT DEFAULT NULL COMMENT \'多图相对路径\', image_tag LONGTEXT DEFAULT NULL COMMENT \'图片的tag信息\', content LONGTEXT DEFAULT NULL COMMENT \'内容\', p_order INT DEFAULT 0 COMMENT \'排序\', share_nums INT DEFAULT 0 COMMENT \'分享次数\', view_auth INT DEFAULT 0 NOT NULL COMMENT \'可见状态0所有，1仅自己\', is_draft INT DEFAULT 0 NOT NULL COMMENT \'是否草稿0否，1是\', enabled INT DEFAULT 0 NOT NULL COMMENT \'发布状态\', disabled INT DEFAULT 0 NOT NULL COMMENT \'是否无效(删除)\', status INT DEFAULT 0 NOT NULL COMMENT \'审核状态(0待审核,1审核通过,2机器拒绝,3待人工审核,4人工拒绝)\', title_status INT DEFAULT 0 NOT NULL COMMENT \'标题审核状态(0待审核,1审核通过,2机器拒绝,3待人工审核,4人工拒绝)\', content_status INT DEFAULT 0 NOT NULL COMMENT \'内容审核状态(0待审核,1审核通过,2机器拒绝,3待人工审核,4人工拒绝)\', image_status INT DEFAULT 0 NOT NULL COMMENT \'图片审核状态(0待审核,1审核通过,2机器拒绝,3待人工审核,4人工拒绝)\', trace_ids LONGTEXT NOT NULL COMMENT \'微信内容审查-图片内容追踪id集合,仅ID ,111:false,2222:false,\', mediacheck_traceid LONGTEXT NOT NULL COMMENT \'微信内容审查-图片内容追踪id集合\', created INT NOT NULL, updated INT DEFAULT NULL, ai_verify_time BIGINT DEFAULT 0 COMMENT \'机器审核时间\', manual_verify_time BIGINT DEFAULT 0 COMMENT \'人工审核时间\', ai_refuse_reason VARCHAR(255) DEFAULT NULL COMMENT \'机器拒绝理由\', manual_refuse_reason VARCHAR(255) DEFAULT NULL COMMENT \'人工拒绝理由\', company_id BIGINT NOT NULL, INDEX idx_user_id (user_id), INDEX idx_company_id (company_id), PRIMARY KEY(post_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'笔记\' ');
        $this->addSql('CREATE TABLE wsugc_post_badge (post_badge_id BIGINT AUTO_INCREMENT NOT NULL, post_id BIGINT NOT NULL COMMENT \'笔记id\', badge_id BIGINT NOT NULL COMMENT \'角标id\', created INT UNSIGNED NOT NULL COMMENT \'添加时间\', company_id BIGINT NOT NULL, INDEX idx_post_id (post_id), INDEX idx_badge_id (badge_id), PRIMARY KEY(post_badge_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'笔记角标\' ');
        $this->addSql('CREATE TABLE wsugc_post_favorite (post_favorite_id BIGINT AUTO_INCREMENT NOT NULL, post_id BIGINT NOT NULL COMMENT \'笔记id\', user_id BIGINT NOT NULL COMMENT \'会员id\', disabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'是否无效\', created bigint NOT NULL, updated bigint NOT NULL, INDEX idx_post_id (post_id), INDEX idx_user_id (user_id), INDEX idx_disabled (disabled), PRIMARY KEY(post_favorite_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'笔记收藏\' ');
        $this->addSql('CREATE TABLE wsugc_post_goods (post_goods_id BIGINT AUTO_INCREMENT NOT NULL, post_id BIGINT NOT NULL COMMENT \'笔记id\', goods_id BIGINT NOT NULL COMMENT \'视频id\', INDEX idx_post_id (post_id), PRIMARY KEY(post_goods_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'笔记\' ');
        $this->addSql('CREATE TABLE wsugc_post_image (post_image_id BIGINT AUTO_INCREMENT NOT NULL, post_id BIGINT DEFAULT 0 COMMENT \'笔记id\', user_id BIGINT DEFAULT 0 COMMENT \'user_id\', image_id BIGINT DEFAULT 0 COMMENT \'image_id\', image_url VARCHAR(255) NOT NULL COMMENT \'图片地址相对\', p_order INT DEFAULT 50 COMMENT \'排序\', activity_joiner_condition LONGTEXT DEFAULT NULL COMMENT \'学员要求\', activity_brief LONGTEXT DEFAULT NULL COMMENT \'活动简介\', yuyue_begin_time INT DEFAULT NULL COMMENT \'活动报名开始时间\', yuyue_end_time INT DEFAULT NULL COMMENT \'活动报名结束时间\', cat_id LONGTEXT DEFAULT NULL COMMENT \'活动类型\', start_time INT NOT NULL COMMENT \'活动开始时间\', end_time INT NOT NULL COMMENT \'活动结束时间\', join_limit INT DEFAULT 0 NOT NULL COMMENT \'可参与次数\', limit_number INT DEFAULT 0 NOT NULL COMMENT \'限制人数\', teacher_title VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'老师头衔\', teacher_name VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'可参与次数\', teacher_brief LONGTEXT NOT NULL COMMENT \'可参与次数\', teacher_avatar VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'可参与次数\', is_sms_notice TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'是否短信通知\', is_wxapp_notice TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'是否小程序模板通知\', enabled INT DEFAULT 1 NOT NULL COMMENT \'是否启用\', created INT NOT NULL, updated INT DEFAULT NULL, company_id BIGINT NOT NULL, INDEX idx_post_id (post_id), PRIMARY KEY(post_image_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'笔记的图片\' ');
        $this->addSql('CREATE TABLE wsugc_post_like (post_like_id BIGINT AUTO_INCREMENT NOT NULL, post_id BIGINT NOT NULL COMMENT \'笔记id\', user_id BIGINT NOT NULL COMMENT \'会员id\', disabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'是否无效\', created bigint NOT NULL, updated bigint NOT NULL, INDEX idx_post_id (post_id), INDEX idx_disabled (disabled), PRIMARY KEY(post_like_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'笔记点赞\' ');
        $this->addSql('CREATE TABLE wsugc_post_reviewlog (log_id BIGINT AUTO_INCREMENT NOT NULL, company_id BIGINT NOT NULL COMMENT \'公司id\', post_id BIGINT DEFAULT NULL COMMENT \'笔记id\', operator_id BIGINT DEFAULT NULL COMMENT \'操作员id\', operator VARCHAR(255) DEFAULT NULL COMMENT \'操作员名称或手机\', user_id BIGINT NOT NULL COMMENT \'用户id\', record_date INT NOT NULL COMMENT \'记录提交日期\', shop_id BIGINT DEFAULT NULL COMMENT \'门店id\', temp_id BIGINT DEFAULT NULL COMMENT \'模板id\', form_data LONGTEXT NOT NULL COMMENT \'记录表单内容\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_post_id (post_id), INDEX idx_company_id (company_id), PRIMARY KEY(log_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'笔记审核日志\' ');
        $this->addSql('CREATE TABLE wsugc_post_topic (post_topic_id BIGINT AUTO_INCREMENT NOT NULL, post_id BIGINT NOT NULL COMMENT \'笔记id\', topic_id VARCHAR(50) NOT NULL COMMENT \'话题id\', created INT UNSIGNED NOT NULL COMMENT \'添加时间\', company_id BIGINT NOT NULL, INDEX idx_post_id (post_id), INDEX idx_topic_id (topic_id), PRIMARY KEY(post_topic_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE wsugc_setting (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', keyname VARCHAR(255) DEFAULT NULL COMMENT \'键名\', value LONGTEXT DEFAULT NULL COMMENT \'值\', type VARCHAR(255) DEFAULT NULL COMMENT \'类型\', company_id BIGINT NOT NULL, created INT UNSIGNED NOT NULL COMMENT \'添加时间\', updated INT DEFAULT NULL, INDEX idx_type (type), INDEX idx_keyname (keyname), INDEX idx_company_id (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'ugc通用设置\' ');
        $this->addSql('CREATE TABLE wsugc_tag (tag_id BIGINT AUTO_INCREMENT NOT NULL, tag_name VARCHAR(250) NOT NULL COMMENT \'标签名称\', mobile VARCHAR(50) DEFAULT NULL COMMENT \'手机号\', user_id BIGINT DEFAULT 0 NOT NULL COMMENT \'创建的用户\', enabled INT DEFAULT 1 NOT NULL COMMENT \'是否启用\', status INT DEFAULT 0 NOT NULL COMMENT \'审核状态(0待审核,1审核通过,2机器拒绝,3待人工审核,4人工拒绝)\', ai_verify_time BIGINT DEFAULT 0 COMMENT \'机器审核时间\', manual_verify_time BIGINT DEFAULT 0 COMMENT \'人工审核时间\', ai_refuse_reason VARCHAR(255) DEFAULT NULL COMMENT \'机器拒绝理由\', manual_refuse_reason VARCHAR(255) DEFAULT NULL COMMENT \'人工拒绝理由\', created INT NOT NULL, p_order INT UNSIGNED DEFAULT 0 NOT NULL COMMENT \'排序\', updated INT DEFAULT NULL, company_id BIGINT NOT NULL, source INT DEFAULT 1 COMMENT \'来源 1用户,2官方\', operator_id BIGINT DEFAULT 0 COMMENT \'管理员id\', INDEX idx_user_id (user_id), INDEX idx_company_id (company_id), INDEX idx_mobile (mobile), PRIMARY KEY(tag_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'图片tag\' ');
        $this->addSql('CREATE TABLE wsugc_topic (topic_id BIGINT AUTO_INCREMENT NOT NULL, topic_name VARCHAR(250) NOT NULL COMMENT \'话题名称\', mobile VARCHAR(50) DEFAULT NULL COMMENT \'手机号\', p_order INT DEFAULT 0 NOT NULL COMMENT \'排序\', created INT UNSIGNED NOT NULL COMMENT \'添加时间\', updated INT DEFAULT NULL, ai_verify_time BIGINT DEFAULT 0 COMMENT \'机器审核时间\', manual_verify_time BIGINT DEFAULT 0 COMMENT \'人工审核时间\', company_id BIGINT NOT NULL, enabled INT DEFAULT 1 NOT NULL COMMENT \'是否启用.\', status INT DEFAULT 0 NOT NULL COMMENT \'审核状态(0待审核,1审核通过,2机器拒绝,3待人工审核,4人工拒绝)\', ai_refuse_reason VARCHAR(255) DEFAULT NULL COMMENT \'机器拒绝理由\', manual_refuse_reason VARCHAR(255) DEFAULT NULL COMMENT \'人工拒绝理由\', is_top INT DEFAULT 0 NOT NULL COMMENT \'是否置顶.\', user_id BIGINT DEFAULT 0 NOT NULL COMMENT \'创建的用户\', source INT DEFAULT 1 COMMENT \'来源 1用户,2官方\', operator_id BIGINT DEFAULT 0 COMMENT \'管理员id\', INDEX idx_user_id (user_id), INDEX idx_company_id (company_id), INDEX idx_mobile (mobile), PRIMARY KEY(topic_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'话题\' ');
        $this->addSql('CREATE INDEX idx_cardid_companyid_userid ON kaquan_user_discount (card_id, company_id, user_id)');
        $this->addSql('ALTER TABLE orders_normal_orders CHANGE discount_fee discount_fee INT DEFAULT 0 NOT NULL COMMENT \'订单优惠金额，以分为单位\'');
        $this->addSql('ALTER TABLE orders_normal_orders_items CHANGE discount_fee discount_fee INT DEFAULT 0 NOT NULL COMMENT \'订单优惠金额，以分为单位\'');
        $this->addSql('ALTER TABLE trade CHANGE discount_fee discount_fee INT DEFAULT 0 NOT NULL COMMENT \'订单优惠金额\'');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema): void
    {
    }
}
