<?php

return [
    'mysql' => [
        'default' => [
            'driver'    => env('DB_DRIVER', 'mysql'),
            'host'      => env('DB_HOST', 'localhost'),
            'port'      => env('DB_PORT', '3306'),
            'database'  => env('DB_DATABASE'),
            'username'  => env('DB_USERNAME'),
            'password'  => env('DB_PASSWORD'),
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
        ],
        'companys' => [
            'driver'    => env('DB_DRIVER', 'mysql'),
            'host'      => env('DB_HOST', 'localhost'),
            'port'      => env('DB_PORT', '3306'),
            'database'  => env('DB_DATABASE'),
            'username'  => env('DB_USERNAME'),
            'password'  => env('DB_PASSWORD'),
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => 'companys',
            'strict'    => false,
        ],
        'datacube' => [
            'driver'    => env('DB_DRIVER', 'mysql'),
            'host'      => env('DB_HOST', 'localhost'),
            'port'      => env('DB_PORT', '3306'),
            'database'  => env('DB_DATABASE'),
            'username'  => env('DB_USERNAME'),
            'password'  => env('DB_PASSWORD'),
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => 'datacube',
            'strict'    => false,
        ],
        'kaquan' => [
            'driver'    => env('DB_DRIVER', 'mysql'),
            'host'      => env('DB_HOST', 'localhost'),
            'port'      => env('DB_PORT', '3306'),
            'database'  => env('DB_DATABASE'),
            'username'  => env('DB_USERNAME'),
            'password'  => env('DB_PASSWORD'),
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => 'kaquan',
            'strict'    => false,
        ],
        'members' => [
            'driver'    => env('DB_DRIVER', 'mysql'),
            'host'      => env('DB_HOST', 'localhost'),
            'port'      => env('DB_PORT', '3306'),
            'database'  => env('DB_DATABASE'),
            'username'  => env('DB_USERNAME'),
            'password'  => env('DB_PASSWORD'),
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => 'members',
            'strict'    => false,
        ],
        'orders' => [
            'driver'    => env('DB_DRIVER', 'mysql'),
            'host'      => env('DB_HOST', 'localhost'),
            'port'      => env('DB_PORT', '3306'),
            'database'  => env('DB_DATABASE'),
            'username'  => env('DB_USERNAME'),
            'password'  => env('DB_PASSWORD'),
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => 'orders',
            'strict'    => false,
        ],
        'wechat' => [
            'driver'    => env('DB_DRIVER', 'mysql'),
            'host'      => env('DB_HOST', 'localhost'),
            'port'      => env('DB_PORT', '3306'),
            'database'  => env('DB_DATABASE'),
            'username'  => env('DB_USERNAME'),
            'password'  => env('DB_PASSWORD'),
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => 'wechat',
            'strict'    => false,
        ],
    ],
    'master_slave'=>[
        'default' => [
            'driver'    => env('DB_DRIVER', 'mysql'),
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
            'wrapperClass' => 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connections\MasterSlaveConnection',
            'driverClass' => 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver',
            'master' => json_decode(env('DB_MASTER'), true),
            'slaves' => json_decode(env('DB_SLAVES'), true),
            
        ],
        'companys' => [
            'driver'    => env('DB_DRIVER', 'mysql'),
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => 'companys',
            'strict'    => false,
            'wrapperClass' => 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connections\MasterSlaveConnection',
            'driverClass' => 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver',
            'master' => json_decode(env('DB_MASTER'), true),
            'slaves' => json_decode(env('DB_SLAVES'), true),
        ],
        'datacube' => [
            'driver'    => env('DB_DRIVER', 'mysql'),
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => 'datacube',
            'strict'    => false,
            'wrapperClass' => 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connections\MasterSlaveConnection',
            'driverClass' => 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver',
            'master' => json_decode(env('DB_MASTER'), true),
            'slaves' => json_decode(env('DB_SLAVES'), true),
        ],
        'kaquan' => [
            'driver'    => env('DB_DRIVER', 'mysql'),
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => 'kaquan',
            'strict'    => false,
            'wrapperClass' => 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connections\MasterSlaveConnection',
            'driverClass' => 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver',
            'master' => json_decode(env('DB_MASTER'), true),
            'slaves' => json_decode(env('DB_SLAVES'), true),
        ],
        'members' => [
            'driver'    => env('DB_DRIVER', 'mysql'),
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => 'members',
            'strict'    => false,
            'wrapperClass' => 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connections\MasterSlaveConnection',
            'driverClass' => 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver',
            'master' => json_decode(env('DB_MASTER'), true),
            'slaves' => json_decode(env('DB_SLAVES'), true),
        ],
        'orders' => [
            'driver'    => env('DB_DRIVER', 'mysql'),
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => 'orders',
            'strict'    => false,
            'wrapperClass' => 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connections\MasterSlaveConnection',
            'driverClass' => 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver',
            'master' => json_decode(env('DB_MASTER'), true),
            'slaves' => json_decode(env('DB_SLAVES'), true),
        ],
        'wechat' => [
            'driver'    => env('DB_DRIVER', 'mysql'),
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => 'wechat',
            'strict'    => false,
            'wrapperClass' => 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connections\MasterSlaveConnection',
            'driverClass' => 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver',
            'master' => json_decode(env('DB_MASTER'), true),
            'slaves' => json_decode(env('DB_SLAVES'), true),
        ],
    ],


];

